- hosts: all
  handlers:
  - name: Restart httpd
    systemd:
      name: httpd
      state: restarted

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: latest
    notify: Restart httpd

  - name: Install php
    yum:
      name: php
      state: latest
    notify: Restart httpd